"""empty message

Revision ID: 165bc66ff482
Revises: 
Create Date: 2023-11-03 17:42:07.932676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165bc66ff482'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cont', sa.Text(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kw', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('男性', '女性', '其他'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('collects',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('keywords_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['tb_content.id'], ),
    sa.ForeignKeyConstraint(['keywords_id'], ['tb_keywords.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['tb_members.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'content_id', 'keywords_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collects')
    op.drop_table('tb_members')
    op.drop_table('tb_keywords')
    op.drop_table('tb_content')
    # ### end Alembic commands ###
